name = "CineFiles"
uuid = "56ba7af4-1aa7-4a85-af25-aa88a55212a9"
authors = ["Alex Ames <alexander.m.ames@gmail.com>, James Bird, and contributors"]
version = "0.2.1"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"

[compat]
ColorTypes = "0.10, 0.11"
ColorVectorSpace = "0.9, 0.10"
FixedPointNumbers = "0.8"
LRUCache = "1.2"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TiffImages = "731e570b-9d59-4bfa-96dc-6df516fadf69"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"

[targets]
test = ["Test", "Glob", "ImageCore", "TiffImages", "XMLDict", "Aqua"]
